added generic items list
OrifInformatique/plafor pull request #102
Opened 2022-01-19 07:56 UTC by maximeor

2022-01-19 08:32 UTC, DidierViret requested changes
Les appels à la liste générique ne fonctionnent pas. Par exemple :
- Dans la liste des plans de formation, un clic sur la poubelle renvoie à la suppression d'un domaine de compétence et pas à la suppression du plan de formation.
- Dans la liste des domaines de compétences, un clic sur le crayon renvoie à l'ajout d'un nouveau domaine de compétence et pas à la modification du domaine de compétence.

Vérifier aussi le fonctionnement de tous les autres boutons des listes.

2022-01-20 12:51 UTC, DidierViret requested changes
**Depuis la liste des plans de formation (courseplan/list_course_plan)**
- si on clique sur la poubelle pour supprimer un plan de formation on arrive sur la suppression d'une formation liée

**Depuis le détail d'un plan de formation (courseplan/view_course_plan)**
- Il n'y a pas la possibilité d'afficher les domaines de compétences qui ont été désactivés

**Depuis le détail d'un domaine de compétence (courseplan/view_competence_domain)**
- Il n'y a pas la possibilité d'afficher les compétences opérationnelles qui ont été désactivées
- si on clique sur la poubelle pour supprimer une compétence opérationnelle puis on clique sur annuler, on se retrouve dans le détail d'un autre domaine de compétence.
- si on clique sur la modification d'une compétence opérationnelle puis on clique sur annuler, on se retrouve dans la liste des plans de formation.
- Pareil si on enregistre les modifications effectuées.

**Depuis le détail d'une compétence opérationnelle (courseplan/view_operational_competence)**
- il n'y a pas la possibilité d'afficher les objectifs qui ont été désactivés

**Détail de l'objectif (courseplan/view_objective)**
- il n'y a pas de raison de garder cette vue car toutes les informations des objectifs apparaissent déjà dans le détail de la compétence opérationnelle

2022-02-01 14:01 UTC, DidierViret requested changes
**Depuis le détail d'un domaine de compétence (courseplan/view_competence_domain)**
- si on clique sur la modification d'une compétence opérationnelle, l'élément sélectionné dans la liste déroulante "Domaine de compétence lié à la compétence opérationnelle" est faux. C'est dans tous les cas le premier domaine de la table de la BD qui apparaît dans cette liste.

2022-02-03 09:14 UTC, DidierViret requested changes

2022-02-03 09:14 UTC, DidierViret commented on orif/plafor/Controllers/CoursePlan.php
> +                    //Reactiver le plan de formation et ses competence et objectifs associés
On ne peut pas faire ça en raison du scénario possible suivant :
1. Il existe un plan de formation actif avec différents domaines de compétences
2. Certains domaines de compétences deviennent obsolète et son désactivés
3. Par erreur quelqu'un désactive le plan de formation puis décide de le réactiver
4. On se retrouve avec tous les domaines de compétences réactivés, y compris ceux qui sont obsolètes

Donc la désactivation/réactivation d'un plan de formation ne doit affecter que le plan de formation et pas les compétences et objectifs qui lui sont liés.

2022-02-03 09:18 UTC, DidierViret requested changes

2022-02-03 09:18 UTC, DidierViret commented on orif/plafor/Controllers/CoursePlan.php
> +                    foreach(CompetenceDomainModel::getOperationalCompetences($competence_domain_id,true) as $operationalCompetence){
La désactivation / réactivation d'un domaine de compétences ne doit affecter que ce domaine de compétences et pas les éléments qui lui sont liés.

2022-02-03 09:38 UTC, DidierViret requested changes

2022-02-03 09:38 UTC, DidierViret commented on orif/plafor/Controllers/CoursePlan.php
> +                    foreach (OperationalCompetenceModel::getObjectives($operational_competence['id'],true) as $objective){
La désactivation / réactivation d'une compétence opérationnelle ne doit affecter que cette compétence opérationnelle et pas les objectifs qui lui sont liés.

2022-02-03 09:38 UTC, DidierViret commented on orif/plafor/Database/Seeds/addAcquisitionStatusDatas.php
>          //Acquisition status//
Pourquoi est-ce qu'on insère des statuts d'acquisition dans la BD ?

2022-02-03 09:38 UTC, DidierViret commented on orif/plafor/Views/course_plan/list.php
> +        <div class="col-sm-9 text-right">
Est-ce que ce fichier est toujours utile maintenant qu'on utilise la liste générique ?

2022-02-03 10:07 UTC, maximeor commented on orif/plafor/Views/course_plan/list.php
> +        <div class="col-sm-9 text-right">
Oui pour afficher le titre de la table et la checkbox afficher desactiver

2022-02-03 10:37 UTC, maximeor commented on orif/plafor/Database/Seeds/addAcquisitionStatusDatas.php
>          //Acquisition status//
Ils ne sont pas nécessaire, c'est juste

2022-02-03 15:07 UTC, DidierViret requested changes

2022-02-03 15:07 UTC, DidierViret commented on orif/plafor/Views/course_plan/list.php
> +        <div class="col-sm-9 text-right">
Ces éléments sont disponibles dans la liste générique, il faudrait vérifier la manière d'utiliser cette liste.

2023-11-09 14:15 UTC, merged