Add the grade feature.
OrifInformatique/plafor pull request #145
Opened 2024-11-20 13:07 UTC by Frankva

Add the grade feature.

2024-11-22 07:15 UTC, derveydylan approved these changes

2024-11-22 14:21 UTC, DidierViret requested changes

2024-11-26 14:58 UTC, DidierViret commented on orif/plafor/Views/grade/save.php
The checkbox is disabled but not checked. It should be checked as this is a "school" grade

2024-11-27 14:21 UTC, Jocelin-T approved these changes
Added/Modified grades with is_school is working (always check and not modifiable)

2024-11-29 11:03 UTC, merged